import React from "react";
import PageIntro from "./PageIntro";
import Icon from "./Icon";
import userData from "@constants/data";

const inquiries = ["Solution architecture", "AI-agent systems", "Speaking & workshops", "Media & interviews"];

export default function Contact() {
  return <><PageIntro eyebrow="Contact" title="Start with the problem worth solving." aside="Email is the quickest path; I typically reply within two business days.">For architecture leadership, AI-agent collaboration, speaking, or a thoughtful technical conversation.</PageIntro><section className="site-container page-section"><div className="grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><a href={`mailto:${userData.email}`} className="paper-card group flex min-h-[300px] flex-col transition hover:-translate-y-1 hover:border-[#91aed2]"><p className="eyebrow">Direct</p><h2 className="mt-4 text-4xl">{userData.email}</h2><p className="mt-4 max-w-xl leading-7 text-[#5f6864] dark:text-[#b7c0bb]">Share the context, desired outcome, and timeline. A concise starting point makes it easier to have a useful first conversation.</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-semibold text-[#174b8b] dark:text-[#a8c7ee]">Start an email <Icon name="arrowRight" /></span></a><div className="paper-card"><p className="eyebrow">Good reasons to reach out</p><ul className="mt-5 divide-y divide-[#d8ddd8] dark:divide-[#34413d]">{inquiries.map((item) => <li key={item} className="py-4 font-semibold">{item}</li>)}</ul></div></div><div className="mt-10 border-t border-[#d8ddd8] pt-8 dark:border-[#34413d]"><p className="eyebrow">Elsewhere</p><div className="mt-3 flex flex-wrap gap-x-6"><a href={userData.socialLinks.linkedin} target="_blank" rel="noopener noreferrer" className="source-label">LinkedIn <Icon name="arrowUpRight" /></a><a href={userData.socialLinks.github} target="_blank" rel="noopener noreferrer" className="source-label">GitHub <Icon name="arrowUpRight" /></a><a href={userData.socialLinks.youtube} target="_blank" rel="noopener noreferrer" className="source-label">YouTube <Icon name="arrowUpRight" /></a></div></div></section></>;
}
